#------------------------------------------------------------------
# Code written by Idris DULAU, Rodin DUHAYON and Guillaume DUBRASQUET-DUVAL.
# Adapted from https://github.com/Chiaraplizz/ST-TR.
# For the use of Dr. Marie Beurton-Aimar and Phd. student Kévin Réby.
#------------------------------------------------------------------

# feeder
feeder: st_gcn.feeder.Feeder_uiprmd
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ../toolsDB/uiprmd_data/train_data_joint.npy
  label_path: ../toolsDB/uiprmd_data/train_label.pkl
test_feeder_args:
  data_path: ../toolsDB/uiprmd_data/val_data_joint.npy
  label_path: ../toolsDB/uiprmd_data/val_label.pkl

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 2
  channel: 3
  window_size: 150
  num_person: 1
  num_point: 22
  dropout: 0
  graph: st_gcn.graph.Uiprmd
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True
  attention: False
  only_attention: True
  tcn_attention: True
  data_normalization: True
  skip_conn: True
  weight_matrix: 2
  only_temporal_attention: True
  bn_flag: True
  attention_3: False
  kernel_temporal: 9
  more_channels: False
  double_channel: True
  drop_connect: True
  concat_original: True
  all_layers: False
  adjacency: False
  agcn: False
  dv: 0.25
  dk: 0.25
  Nh: 8
  n: 4
  dim_block1: 10
  dim_block2: 30
  dim_block3: 75
  relative: False
  visualization: False

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [45, 55]

# training
device: [0, 1, 2, 3]
batch_size: 32
test_batch_size: 1
num_epoch: 3
nesterov: True
